name: Dependency Check

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  check-dependencies:
    name: Check for Updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for outdated packages
        id: outdated
        run: |
          echo "## Outdated Packages Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
          npm outdated >> $GITHUB_STEP_SUMMARY 2>&1 || true
          echo "```" >> $GITHUB_STEP_SUMMARY

      - name: Security audit
        id: audit
        run: |
          echo "## Security Audit Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
          npm audit >> $GITHUB_STEP_SUMMARY 2>&1 || true
          echo "```" >> $GITHUB_STEP_SUMMARY

      - name: Create issue for critical updates
        uses: actions/github-script@v7
        with:
          script: |
            const date = new Date().toISOString().split('T')[0];
            const title = `Weekly Dependency Update Report - ${date}`;

            // Check if issue already exists
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: ['dependencies', 'automated']
            });

            const existingIssue = issues.data.find(issue =>
              issue.title.startsWith('Weekly Dependency Update Report')
            );

            if (!existingIssue) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: `## 📦 Dependency Update Report

                  This is an automated weekly check of project dependencies.

                  ### Actions Required:
                  1. Review outdated packages
                  2. Check for security vulnerabilities
                  3. Plan updates for critical packages

                  ### Reports:
                  - See the [workflow run summary](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details
                  - Run \`npm outdated\` locally for full report
                  - Run \`npm audit\` for security details

                  ### Priority Updates:
                  - Framework updates (Next.js, React)
                  - Security patches
                  - Major version updates requiring migration

                  ---
                  *This issue was automatically created by the dependency check workflow.*`,
                labels: ['dependencies', 'automated', 'maintenance']
              });
            }

  update-minor:
    name: Auto-update Minor Versions
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Update minor and patch versions
        run: |
          npx npm-check-updates -u --target minor
          npm install

      - name: Run tests after update
        run: npm test -- --watchAll=false
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update minor and patch dependencies'
          title: '[Auto] Update Minor Dependencies'
          body: |
            ## 🔄 Automatic Dependency Update

            This PR updates minor and patch versions of dependencies.

            ### Changes:
            - Updated minor and patch versions only
            - No breaking changes expected
            - Tests have been run automatically

            ### Review Checklist:
            - [ ] Review package changes
            - [ ] Verify tests pass
            - [ ] Check for any warnings
            - [ ] Test locally if needed

            ---
            *This PR was automatically created by the dependency update workflow.*
          branch: auto-update-dependencies
          labels: |
            dependencies
            automated
            minor-update

